#!/bin/sh

set -eu
umask 077

CPUS="2"
DISK="20"
GRAPHICS="none"
MEMORY="2048"
NETWORK="network=default"
RELEASE="7.7"
TITLE="OpenBSD"

while getopts c:d:m:n: OPT; do
    case "$OPT" in
        c)
            CPUS="$OPTARG"
            ;;
        d)
            DISK="$OPTARG"
            ;;
        m)
            MEMORY="$OPTARG"
            ;;
        n)
            NETWORK="$OPTARG"
            ;;
        *)
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

NAME="$1"
shift

# use the latest available openbsd
OSINFO="$(osinfo-query -f short-id os | awk '/openbsd[0-9]/ { print $1 }' | tail -1)"
[ -n "$OSINFO" ] || exit 1

TEMP="$(mktemp -d)"
trap 'rm -fr ${TEMP}' EXIT

URL="https://cdn.openbsd.org/pub/OpenBSD/${RELEASE}/amd64/cd$(echo "$RELEASE" | tr -d .).iso"
ISO="${TEMP}/$(basename "$URL")"

set -x

curl -o "$ISO" "$URL"
chmod -R a+rX "$TEMP"

virt-install \
    --name "$NAME" \
    --memory "$MEMORY" \
    --metadata "title=${TITLE} ${RELEASE}" \
    --vcpus "sockets=1,cores=${CPUS},threads=1" \
    --cpu "host-passthrough" \
    --cdrom "$ISO" \
    --boot "useserial=on" \
    --osinfo "$OSINFO" \
    --disk "cache=none,format=raw,size=${DISK}" \
    --network "$NETWORK" \
    --graphics "$GRAPHICS" \
    --controller "type=usb,model=none" \
    "$@"
